# Generated by Django 5.2.8 on 2025-12-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
