# Generated by Django 5.2.8 on 2025-12-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="face_image",
            field=models.ImageField(upload_to="students/faces/"),
        ),
    ]
