# Generated by Django 5.2.8 on 2026-01-18 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_face_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='face_embedding',
            new_name='face_embeddings',
        ),
        migrations.RemoveField(
            model_name='student',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
