# Generated by Django 6.0.1 on 2026-02-04 07:11

import django.utils.timezone
from django.db import migrations, models
from collections import defaultdict


def populate_date_field(apps, schema_editor):
    """Populate the date field from the timestamp field for existing records."""
    Attendance = apps.get_model('attendance', 'Attendance')
    for attendance in Attendance.objects.all():
        attendance.date = attendance.timestamp.date()
        attendance.save(update_fields=['date'])


def remove_duplicates(apps, schema_editor):
    """Remove duplicate attendance records, keeping only the first per (student, classroom, date)."""
    Attendance = apps.get_model('attendance', 'Attendance')
    
    # Group by (student, classroom, date)
    groups = defaultdict(list)
    for record in Attendance.objects.all().order_by('id'):
        key = (record.student_id, record.classroom_id, record.date)
        groups[key].append(record)
    
    # Delete duplicates (keep the first one)
    for key, items in groups.items():
        if len(items) > 1:
            for duplicate in items[1:]:
                duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together_and_more'),
        ('classrooms', '0002_classroom_capacity'),
        ('students', '0004_student_user'),
    ]

    operations = [
        # Step 1: Add the date field (nullable initially)
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        # Step 2: Populate date field from timestamp
        migrations.RunPython(populate_date_field, migrations.RunPython.noop),
        # Step 3: Remove duplicates
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        # Step 4: Add unique constraint
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classroom', 'date')},
        ),
    ]

